import subprocess
import os

def plink_roh(
        input_file: str, output_folder: str, plink_path: str ="./plink",
        window_snp: int = 50, window_het: int = 1, window_missing: int = 5, window_threshold: float = 0.05,
        homozyg_gap: int = 1000, homozyg_het: int = 1000, homozyg_density: int = 50, homozyg_snp: int = 100, homozyg_kb: int = 1000
    ) -> None:

    """
    Sends a file to PLINK for Run of Homozygosity (RoH) analysis.

    Args:
        Filesystem:
            input_file (str):               Path to the input file for PLINK, without extension
            output_prefix (str):            Prefix for the output files generated by PLINK
            plink_path (str):               Path to the PLINK executable (default: "plink")
        PLINK Parameters (with default values):
            Defining the scanning window:
                window_snp (int):           Size of the scanning window in SNPs (default: 50)
                window_het (int):           Maximum number of heterozygous calls allowed in the scanning window (default: 1)
                window_missing (int):       Maximum number of missing calls allowed in the scanning window (default: 5)
                window_threshold (float):   Minimum scanning window hit rate (default: 0.05)
            Tresholds for calling a homozygous segment:
                homozyg_gap (int):          Maximum interval between two SNPs in a segment in kilobases (default: 1000)
                homozyg_het (int):          Maximum number of heterozygous calls in a homozygous segment (default: 1000) - This flag is disabled by default in PLINK
                homozyg_density (int):      Maximum inverse density of a homozygous segment (default: 50)
                homozyg_snp (int):          Minimum number of SNPs in a homozygous segment (default: 100)
                homozyg_kb (int):           Minimum length of a homozygous segment in kilobases (default: 1000)

    Outputs:
        Generates output files in the specified output folder:
            .hh         	                List of het. haploid and nonmale Ychr genotypes.
            .hom	                        Run-of-homozygosity list.
            .hom.indiv		                Sample-based runs-of-homozygosity report.
            .hom.summary    	            SNP-based runs-of-homozygosity report.
    """

    if not os.path.exists(input_file + ".tped"):
        raise FileNotFoundError(f"Input file '{input_file}' does not exist.")

    # Construct the PLINK command
    roh_command = [
        plink_path,
        "--tfile", input_file,
        "--dog",
        "--homozyg",
        "--homozyg-window-snp", str(window_snp),
        "--homozyg-window-het", str(window_het),
        "--homozyg-window-missing", str(window_missing),
        "--homozyg-window-threshold", str(window_threshold),
        "--homozyg-gap", str(homozyg_gap),
        "--homozyg-het", str(homozyg_het),
        "--homozyg-density", str(homozyg_density),
        "--homozyg-snp", str(homozyg_snp),
        "--homozyg-kb", str(homozyg_kb),
        "--out", output_folder
    ]

    try:
        # Execute the PLINK command
        result = subprocess.run(roh_command, check=True, text=True, capture_output=True)
        print("PLINK output:")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("Error running PLINK:")
        print(e.stderr)
        raise
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise

if __name__ == "__main__":
    # Example usage
    input_file = "/path/to/input_file"  # Replace with your input file path
    output_folder = "/path/to/output_prefix"  # Replace with your desired output prefix
    plink_path = "plink"  # Adjust if PLINK is not in your PATH

    try:
        plink_roh(input_file, output_folder, plink_path)
    except Exception as e:
        print(f"Failed to send file to PLINK: {e}")