import subprocess
import os

def _plink_merge_bim_files(bim_file_main: str, bim_files_to_merge: list, output_bim_file: str, plink_path: str ="./plink") -> str:
    """
    Merges two bim files using PLINK.

    Args:
        bim_file_main (str): The path to the main BIM file (without extension).
        bim_file_to_merge (str): The path to the file to merge (without extension).
        plink_path (str): The path to the PLINK executable (default: "./plink").

    Returns:
        str: The path to the merged BIM file (without extension).
    """

    bim_list = bim_file_main + "_list_to_merge.txt"
    with open(bim_list, 'w') as f:
        for bim_file in bim_files_to_merge:
            f.write(f"{bim_file}\n")

    merge_command = [
        plink_path,
        "--dog",
        "--bfile", bim_file_main,
        "--merge-list", bim_list,
        "--out", output_bim_file
    ]

    try:
        # Execute the PLINK command
        result = subprocess.run(merge_command, check=True, text=True, capture_output=True)
        print("PLINK output:")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("Error running PLINK:")
        print(e.stderr)
        raise
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise
    return output_bim_file

def _plink_convert_tped_to_bim(tped_file: str, plink_path: str="./plink") -> None:
    """
    Converts a TPED file to bim format using PLINK.

    Args:
        tped_file (str): The path to the TPED file (without extension).
        plink_path (str): The path to the PLINK executable.
        output_file (str): The desired output BIM file path (without extension).
    """

    convert_command = [
        plink_path,
        "--dog",
        "--tfile", tped_file,
        "--make-bed",
        "--out", tped_file
    ]

    try:
        # Execute the PLINK command
        result = subprocess.run(convert_command, check=True, text=True, capture_output=True)
        print("PLINK output:")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("Error running PLINK:")
        print(e.stderr)
        raise
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise

def plink_roh(input_file: str, output_folder: str, plink_path: str ="./plink",
        window_snp: int = 50, window_het: int = 1, window_missing: int = 5, window_threshold: float = 0.05,
        homozyg_gap: int = 1000, homozyg_het: int = 1000, homozyg_density: int = 50, homozyg_snp: int = 100, homozyg_kb: int = 1000
    ) -> None:

    """
    Sends a file to PLINK for Run of Homozygosity (RoH) analysis.

    Args:
        Filesystem:
            input_file (str):               Path to the input file for PLINK, without extension
            output_prefix (str):            Prefix for the output files generated by PLINK
            plink_path (str):               Path to the PLINK executable (default: "plink")
        PLINK Parameters (with default values):
            Defining the scanning window:
                window_snp (int):           Size of the scanning window in SNPs (default: 50)
                window_het (int):           Maximum number of heterozygous calls allowed in the scanning window (default: 1)
                window_missing (int):       Maximum number of missing calls allowed in the scanning window (default: 5)
                window_threshold (float):   Minimum scanning window hit rate (default: 0.05)
            Tresholds for calling a homozygous segment:
                homozyg_gap (int):          Maximum interval between two SNPs in a segment in kilobases (default: 1000)
                homozyg_het (int):          Maximum number of heterozygous calls in a homozygous segment (default: 1000) - This flag is disabled by default in PLINK
                homozyg_density (int):      Maximum inverse density of a homozygous segment (default: 50)
                homozyg_snp (int):          Minimum number of SNPs in a homozygous segment (default: 100)
                homozyg_kb (int):           Minimum length of a homozygous segment in kilobases (default: 1000)

    Outputs:
        Generates output files in the specified output folder:
            .hh         	                List of het. haploid and nonmale Ychr genotypes.
            .hom	                        Run-of-homozygosity list.
            .hom.indiv		                Sample-based runs-of-homozygosity report.
            .hom.summary    	            SNP-based runs-of-homozygosity report.
    """

    if not os.path.exists(input_file + ".tped"):
        raise FileNotFoundError(f"Input file '{input_file}' does not exist.")

    # Construct the PLINK command
    roh_command = [
        plink_path,
        "--tfile", input_file,
        "--dog",
        "--homozyg",
        "--homozyg-window-snp", str(window_snp),
        "--homozyg-window-het", str(window_het),
        "--homozyg-window-missing", str(window_missing),
        "--homozyg-window-threshold", str(window_threshold),
        "--homozyg-gap", str(homozyg_gap),
        "--homozyg-het", str(homozyg_het),
        "--homozyg-density", str(homozyg_density),
        "--homozyg-snp", str(homozyg_snp),
        "--homozyg-kb", str(homozyg_kb),
        "--out", output_folder
    ]

    try:
        # Execute the PLINK command
        result = subprocess.run(roh_command, check=True, text=True, capture_output=True)
        print("PLINK output:")
        print(result.stdout)
    except subprocess.CalledProcessError as e:
        print("Error running PLINK:")
        print(e.stderr)
        raise
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        raise

def plink_parentage(offspring_file: str, parent1_file: str, parent2_file: str, plink_path: str ="./plink") -> None:
    """
    Sends the target individual and potential parents' files to PLINK for parentage analysis.

    Args:
        offspring_file (str): The path to the file containing the offspring's genotypes.
        parent1_file (str): The path to the file containing the first parent's genotypes.
        parent2_file (str): The path to the file containing the second parent's genotypes.
        plink_path (str): The path to the PLINK executable (default: "./plink").
    """

    if not os.path.exists(offspring_file + ".tped"):
        raise FileNotFoundError(f"Offspring file '{offspring_file}' does not exist.")
    if not os.path.exists(parent1_file + ".tped"):
        raise FileNotFoundError(f"Parent 1 file '{parent1_file}' does not exist.")
    if not os.path.exists(parent2_file + ".tped"):
        raise FileNotFoundError(f"Parent 2 file '{parent2_file}' does not exist.")

    # Converts tped files to bim files
    _plink_convert_tped_to_bim(
        tped_file=offspring_file,
        plink_path=plink_path
    )
    _plink_convert_tped_to_bim(
        tped_file=parent1_file,
        plink_path=plink_path
    )
    _plink_convert_tped_to_bim(
        tped_file=parent2_file,
        plink_path=plink_path
    )

    # Merges parents' bim files with offspring bim file
    output_bim_file = os.path.splitext(offspring_file)[0] + "_merged"

    _plink_merge_bim_files(
        bim_file_main=offspring_file,
        bim_files_to_merge=[parent1_file, parent2_file],
        plink_path=plink_path,
        output_bim_file=output_bim_file
    )

    # # Construct the PLINK command
    # roh_command = [
    #     plink_path,
    #     "--dog",
    #     "--file", offspring_file + "_merged",
    #     "--genome"
    # ]

    # try:
    #     # Execute the PLINK command
    #     result = subprocess.run(roh_command, check=True, text=True, capture_output=True)
    #     print("PLINK output:")
    #     print(result.stdout)
    # except subprocess.CalledProcessError as e:
    #     print("Error running PLINK:")
    #     print(e.stderr)
    #     raise
    # except Exception as e:
    #     print(f"An unexpected error occurred: {e}")
    #     raise

if __name__ == "__main__":
    # Example usage
    input_file = "/path/to/input_file"  # Replace with your input file path
    output_folder = "/path/to/output_prefix"  # Replace with your desired output prefix
    plink_path = "plink"  # Adjust if PLINK is not in your PATH

    try:
        plink_roh(input_file, output_folder, plink_path)
    except Exception as e:
        print(f"Failed to send file to PLINK: {e}")